/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tbs.companyclient;

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tom
 */
public class EmployeeDialog extends javax.swing.JFrame {
  
  public enum DialogMode {
    CREATE,UPDATE
  }
  
  private int employeeId;
  private DialogMode dialogMode;
  private EmployeeCallback callback;
  
  /**
   * Creates new form EmployeeDialog
   */
  public EmployeeDialog() {
    initComponents();
  }
  
  public EmployeeDialog(EmployeeCallback callback) {
    initComponents();
    List<Department> departmentList = CompanyRESTfulClient.readAllDepartments();
    Vector<String> departmentVector = getDepartmentsFromDatabase(departmentList);
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(departmentVector);
    departmentComboBox.setModel(comboBoxModel);
    departmentComboBox.setSelectedIndex(0);
    dialogMode = DialogMode.CREATE;
    this.callback = callback;
  }

  public EmployeeDialog(Employee employee, EmployeeCallback callback) {
    initComponents();
    employeeId = employee.getId();
    nameTextField.setText(employee.getName());
    extensionTextField.setText(String.format("%d",employee.getExtension()));
    emailTextField.setText(employee.getEmail());
    startDateTextField.setText(employee.getStartDate());
    List<Department> departmentList = CompanyRESTfulClient.readAllDepartments();
    Vector<String> departmentVector = getDepartmentsFromDatabase(departmentList);
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(departmentVector);
    departmentComboBox.setModel(comboBoxModel);
    int departmentIndex = getDepartmentIndexBinarySearch(departmentList, employee.getDepartmentId());
    departmentComboBox.setSelectedIndex(departmentIndex);
    dialogMode = DialogMode.UPDATE;
    this.callback = callback;
  }
  
  private Vector<String> getDepartmentsFromDatabase(List<Department> departmentList) {
    Vector<String> departmentVector = new Vector<>();
    for(Department department : departmentList)
      departmentVector.add(department.getName());
    return departmentVector;
  }
  
  private static int getDepartmentIndex(List<Department> departmentList, int departmentId) {
    // Optimization Binary Search
    int count = 0;
    for(Department department : departmentList) {
      if(department.id == departmentId) break;
      count++;
    }
    return count;
  }
  
  private static int getDepartmentIndexBinarySearch(List<Department> departmentList, int departmentId) {
    // Ensure that the list is sorted by department id
    Collections.sort(departmentList, Comparator.comparingInt(Department::getId));
    // Perform binary search
    int low = 0;
    int high = departmentList.size() - 1;
    while (low <= high) {
      int mid = low + (high - low) / 2;
      Department department = departmentList.get(mid);
      if (department.getId() == departmentId) {
        return mid; // Return the index of the found department
      }
      else if (department.getId() < departmentId) {
        low = mid + 1;
      }
      else {
        high = mid - 1;
      }
    }
    return -1; // Department not found
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    extensionTextField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    emailTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    startDateTextField = new javax.swing.JTextField();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    departmentComboBox = new javax.swing.JComboBox<>();
    nameTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Name");

    jLabel3.setText("Extension");

    jLabel4.setText("E-Mail");

    jLabel5.setText("Start Date");

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    jLabel6.setText("Employee Dialog");

    jLabel7.setText("Department");

    departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(29, 29, 29)
            .addComponent(nameTextField))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(okButton)
            .addGap(18, 18, 18)
            .addComponent(cancelButton))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
              .addComponent(jLabel7))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(extensionTextField)
              .addComponent(emailTextField)
              .addComponent(startDateTextField)
              .addComponent(departmentComboBox, 0, 405, Short.MAX_VALUE))))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel4, jLabel5});

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel6)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(extensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(okButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    try {
      int extension = Integer.valueOf(extensionTextField.getText());
      Employee employee = new Employee(employeeId, nameTextField.getText(), extension, emailTextField.getText(), startDateTextField.getText(), departmentComboBox.getSelectedIndex());
      switch(dialogMode) {
        case DialogMode.CREATE:
          callback.createEmployeeCallback(employee);
          break;
        case DialogMode.UPDATE:
          callback.updateEmployeeCallback(employee);
          break;
      }
      dispose();
    }
    catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(null, "Invalid extension input!", "Error", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new EmployeeDialog().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JComboBox<String> departmentComboBox;
  private javax.swing.JTextField emailTextField;
  private javax.swing.JTextField extensionTextField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField startDateTextField;
  // End of variables declaration//GEN-END:variables
}
